import Foundation
import Combine

/// The central state container for the Niblet app session.
///
/// `NibletAppState` is the single source of truth for everything happening during the current app session.
/// It manages the flow of data through a user interaction:
/// 1. User selects input text
/// 2. User picks a Nibble (action)
/// 3. AI generates a response
/// 4. Result is saved as a Crumb in history
///
/// **Relationships:**
/// - Holds all `NibbleAction` templates available to the user
/// - Tracks the currently selected `NibbleAction` that's being used
/// - Records completed interactions as `Crumb` objects in the history
/// - Observed by SwiftUI views via `@ObservedObject` or environment injection
/// - Uses `@MainActor` to ensure all state updates happen on the main thread (required by SwiftUI)
/// - Uses `@Published` so any view observing this state automatically refreshes when properties change
///
/// **Typical Flow:**
/// - View calls `selectNibble(_:)` → sets `selectedNibble`
/// - View calls `startGenerating()` → sets `isGenerating = true`
/// - AI service processes the prompt
/// - View calls `finishGenerating(response:)` → saves response, stops loading, creates Crumb
/// - User can call `clearResponse()` to reset for next action or `clearHistory()` to wipe history
@MainActor
final class NibletAppState: ObservableObject {
    /// The current text the user wants to process
    /// Typically selected text from another app or pasted manually
    /// Starts with placeholder text for preview/demo purposes
    @Published var currentInputText: String = """
    Niblet is a tiny AI palette for your Mac. Select text, press a shortcut, and choose a bite-sized action.
    """

    /// The Nibble (action) the user has selected to run
    /// Nil if no action is currently selected
    /// Determines which prompt template gets used when AI generates a response
    @Published var selectedNibble: NibbleAction?
    
    /// The AI-generated response text from the last action
    /// Empty string initially or after clearing
    /// Populated when `finishGenerating(response:)` is called
    @Published var responseText: String = ""
    
    /// Whether an AI response is currently being generated
    /// True while the AI is processing, false when idle or done
    /// Views use this to show loading spinners or disable buttons
    @Published var isGenerating: Bool = false
    
    /// In-memory history of all completed interactions in this session
    /// Each item is a Crumb (a saved input/output pair)
    /// Newest items first (inserted at index 0)
    /// Cleared when app quits or user explicitly clears history
    @Published var crumbs: [Crumb] = []

    /// All available Nibble templates that the user can choose from
    /// Loaded once from NibbleAction.samples
    /// Doesn't change during a session
    let availableNibbles: [NibbleAction] = NibbleAction.samples

    /// Set the active Nibble and clear any previous response
    /// Called when user picks an action from the UI
    func selectNibble(_ nibble: NibbleAction) {
        selectedNibble = nibble
        responseText = ""
    }

    /// Update the current input text
    /// Called as user edits the text field
    func updateInputText(_ text: String) {
        currentInputText = text
    }

    /// Mark that AI generation has started
    /// Sets loading state and clears previous response
    /// Call this before sending a request to the AI service
    func startGenerating() {
        isGenerating = true
        responseText = ""
    }

    /// Record the AI's response and finish generating
    /// Creates and saves a Crumb to history
    /// Called when AI service returns a response
    /// - Parameter response: The text generated by the AI
    func finishGenerating(response: String) {
        responseText = response
        isGenerating = false

        guard let selectedNibble else {
            return
        }

        let crumb = Crumb(
            inputText: currentInputText,
            nibbleID: selectedNibble.id,
            nibbleTitle: selectedNibble.title,
            responseText: response
        )

        crumbs.insert(crumb, at: 0)
    }

    /// Clear the current response and selected action
    /// Resets the UI to initial state without clearing history
    /// Called when user clicks "Clear" or starts a new action
    func clearResponse() {
        selectedNibble = nil
        responseText = ""
        isGenerating = false
    }

    /// Erase all saved Crumbs (history)
    /// Called when user explicitly wants to clear their history
    /// Cannot be undone in the current session
    func clearHistory() {
        crumbs.removeAll()
    }
}
